---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolexsun-resume-759d6596
  labels:
    app: rolexsun-resume-759d6596
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rolexsun-resume-759d6596
  template:
    metadata:
      labels:
        app: rolexsun-resume-759d6596
    spec:
      serviceAccountName: ingress-manager
      containers:
        - name: rolexsun-resume-759d6596
          image: docker.io/phengbunath/rolexsun-resume-759d6596:1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
